(()=>{'use strict';
const RE=6378.137,RP=6356.752314245,MU=398600.4418,J2=1.08262668e-3,EARTH_DAY=86164.0905,TAU=Math.PI*2,VIS_RE=5,SCALE=VIS_RE/RE,FLAT=RP/RE,START=Date.UTC(2026,6,10,12,0,0);
const $=id=>document.getElementById(id),rad=d=>d*Math.PI/180,deg=r=>r*180/Math.PI,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),wrap=a=>(a%TAU+TAU)%TAU;
const warpValues=[0,1,10,120,600,1800,7200];
const state={running:true,simTime:0,warpIndex:3,earthAngle:0,rotation:true,scan:true,footprint:true,camera:'global',lastScan:null};
const scene=new THREE.Scene(),container=$('space');
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.001,350);camera.position.set(12,6.8,12.5);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;container.appendChild(renderer.domElement);
const controls=new THREE.OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.055;controls.minDistance=5.18;controls.maxDistance=52;controls.enablePan=false;

const manager=new THREE.LoadingManager();manager.onLoad=()=>{setTimeout(()=>$('loader').classList.add('hide'),350);toast('Blue Marble y topografía cargados')};manager.onError=url=>{console.error('No se pudo cargar',url);$('loader').querySelector('.loaderText').innerHTML='<b>ERROR DE RECURSOS</b>ABRE EL PROYECTO SIN SEPARAR LA CARPETA ASSETS'};
const loader=new THREE.TextureLoader(manager);
function texture(path,srgb=true){const t=loader.load(path);t.anisotropy=renderer.capabilities.getMaxAnisotropy();if(srgb)t.encoding=THREE.sRGBEncoding;return t}
const maps={day:texture('assets/earth-blue-marble.jpg'),night:texture('assets/earth-night.jpg'),height:texture('assets/earth-topology.png',false),water:texture('assets/earth-water.png',false),cloud:texture('assets/clouds.png'),sky:texture('assets/night-sky.png')};
maps.sky.mapping=THREE.EquirectangularReflectionMapping;scene.background=maps.sky;

scene.add(new THREE.AmbientLight(0x142432,.12));
const sunLight=new THREE.DirectionalLight(0xfff2d2,3.4);sunLight.target.position.set(0,0,0);scene.add(sunLight,sunLight.target);
const earthGroup=new THREE.Group();scene.add(earthGroup);
const earthGeo=new THREE.SphereGeometry(VIS_RE,256,144);
const earthMat=new THREE.MeshPhongMaterial({map:maps.day,bumpMap:maps.height,bumpScale:.055,displacementMap:maps.height,displacementScale:.055,specularMap:maps.water,specular:new THREE.Color(0x95bfd1),shininess:26});
const earth=new THREE.Mesh(earthGeo,earthMat);earth.scale.y=FLAT;earthGroup.add(earth);

const nightUniforms={lightsMap:{value:maps.night},heightMap:{value:maps.height},sunDirection:{value:new THREE.Vector3(1,0,0)},dispScale:{value:.055}};
const nightMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:nightUniforms,vertexShader:`uniform sampler2D heightMap;uniform float dispScale;varying vec2 vUv;varying vec3 vWorldNormal;void main(){vUv=uv;vec3 p=position+normal*(texture2D(heightMap,uv).r*dispScale+.004);vWorldNormal=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}`,fragmentShader:`uniform sampler2D lightsMap;uniform vec3 sunDirection;varying vec2 vUv;varying vec3 vWorldNormal;void main(){vec3 tex=texture2D(lightsMap,vUv).rgb;float lum=max(tex.r,max(tex.g,tex.b));float darkness=smoothstep(.12,-.22,dot(normalize(vWorldNormal),normalize(sunDirection)));float lights=smoothstep(.09,.72,lum);gl_FragColor=vec4(tex*(1.15+lights*1.8),darkness*lights*.95);}`});
const nightLayer=new THREE.Mesh(earthGeo.clone(),nightMat);nightLayer.scale.y=FLAT;earthGroup.add(nightLayer);
const cloudMat=new THREE.MeshPhongMaterial({map:maps.cloud,transparent:true,opacity:.62,depthWrite:false,blending:THREE.NormalBlending});
const clouds=new THREE.Mesh(new THREE.SphereGeometry(5.085,192,108),cloudMat);clouds.scale.y=FLAT;earthGroup.add(clouds);
const atmoMat=new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,blending:THREE.AdditiveBlending,depthWrite:false,uniforms:{glowColor:{value:new THREE.Color(0x36bde8)},sunDirection:{value:new THREE.Vector3(1,0,0)}},vertexShader:`varying vec3 nW;varying vec3 pW;void main(){nW=normalize(mat3(modelMatrix)*normal);vec4 w=modelMatrix*vec4(position,1.);pW=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`uniform vec3 glowColor;uniform vec3 sunDirection;varying vec3 nW;varying vec3 pW;void main(){vec3 V=normalize(cameraPosition-pW);float rim=pow(1.0-clamp(dot(nW,V),0.0,1.0),3.0);float daylight=.22+.78*smoothstep(-.35,.25,dot(nW,sunDirection));gl_FragColor=vec4(glowColor,rim*daylight*.72);}`});
const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(5.19,128,80),atmoMat);atmosphere.scale.y=FLAT;earthGroup.add(atmosphere);
const sunSprite=(()=>{const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),g=x.createRadialGradient(128,128,1,128,128,126);g.addColorStop(0,'#fff');g.addColorStop(.055,'rgba(255,243,198,.98)');g.addColorStop(.19,'rgba(255,177,72,.35)');g.addColorStop(1,'rgba(255,115,20,0)');x.fillStyle=g;x.fillRect(0,0,256,256);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));s.scale.set(10,10,1);scene.add(s);return s})();

const scanCanvas=document.createElement('canvas');scanCanvas.width=2048;scanCanvas.height=1024;const sx=scanCanvas.getContext('2d'),scanTex=new THREE.CanvasTexture(scanCanvas);scanTex.minFilter=THREE.LinearFilter;
const scanSphere=new THREE.Mesh(new THREE.SphereGeometry(5.075,192,108),new THREE.MeshBasicMaterial({map:scanTex,transparent:true,opacity:.67,depthWrite:false,blending:THREE.AdditiveBlending}));scanSphere.scale.y=FLAT;earthGroup.add(scanSphere);
const cols=720,rows=360,coverageGrid=new Uint8Array(cols*rows),rowWeights=Array.from({length:rows},(_,r)=>Math.cos(((r+.5)/rows-.5)*Math.PI));let totalWeight=rowWeights.reduce((s,w)=>s+w*cols,0),coveredWeight=0;

function satelliteModel(){const g=new THREE.Group(),gold=new THREE.MeshStandardMaterial({color:0xd9b96a,metalness:.9,roughness:.2}),dark=new THREE.MeshStandardMaterial({color:0x061018,metalness:.72,roughness:.22}),blue=new THREE.MeshStandardMaterial({color:0x164f92,metalness:.62,roughness:.2,emissive:0x082450,emissiveIntensity:.72});const body=new THREE.Mesh(new THREE.BoxGeometry(.15,.18,.25),gold),lens=new THREE.Mesh(new THREE.CylinderGeometry(.055,.08,.11,24),dark);lens.rotation.x=Math.PI/2;lens.position.z=.17;const pg=new THREE.BoxGeometry(.48,.012,.15),p1=new THREE.Mesh(pg,blue),p2=p1.clone();p1.position.x=.31;p2.position.x=-.31;g.add(body,lens,p1,p2);return g}
const sat=satelliteModel();scene.add(sat);sat.add(new THREE.PointLight(0x55e7ff,.7,2));
const orbitLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0x55e7ff,transparent:true,opacity:.4}));scene.add(orbitLine);
const trackLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0x73ffad,transparent:true,opacity:.72}));earthGroup.add(trackLine);let trackPoints=[];
const cone=new THREE.Mesh(new THREE.ConeGeometry(1,1,64,1,true),new THREE.MeshBasicMaterial({color:0x53e8ff,transparent:true,opacity:.16,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));scene.add(cone);
const footprint=new THREE.Mesh(new THREE.RingGeometry(.84,1,96),new THREE.MeshBasicMaterial({color:0x7dffb2,transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false}));scene.add(footprint);

function julian(date){return date.getTime()/86400000+2440587.5}
function gmst(date){const jd=julian(date),T=(jd-2451545)/36525;return rad(wrap(rad(280.46061837+360.98564736629*(jd-2451545)+.000387933*T*T-T*T*T/38710000))*180/Math.PI)}
function sunVector(date){const n=julian(date)-2451545,L=wrap(rad(280.460+0.9856474*n)),gg=wrap(rad(357.528+0.9856003*n)),lambda=L+rad(1.915)*Math.sin(gg)+rad(.020)*Math.sin(2*gg),eps=rad(23.439-.0000004*n),ra=Math.atan2(Math.cos(eps)*Math.sin(lambda),Math.cos(lambda)),dec=Math.asin(Math.sin(eps)*Math.sin(lambda));return new THREE.Vector3(Math.cos(dec)*Math.cos(ra),Math.sin(dec),Math.cos(dec)*Math.sin(ra)).normalize()}
function elements(t=state.simTime){const e=+$('eccentricity').value,rp=RE+(+$('altitude').value),a=rp/(1-e),i=rad(+$('inclination').value),p=a*(1-e*e),n=Math.sqrt(MU/(a*a*a));let O=rad(+$('raan').value),w=rad(+$('argPerigee').value);if($('j2Toggle').classList.contains('on')){O+=-1.5*J2*n*(RE/p)**2*Math.cos(i)*t;w+=.75*J2*n*(RE/p)**2*(5*Math.cos(i)**2-1)*t}return{e,a,i,p,n,O,w,rp,ra:a*(1+e)}}
function solveKepler(M,e){M=wrap(M);let E=e<.8?M:Math.PI;for(let k=0;k<8;k++)E-=(E-e*Math.sin(E)-M)/(1-e*Math.cos(E));return E}
function eciFromTrue(f,el){const r=el.p/(1+el.e*Math.cos(f)),u=el.w+f,cO=Math.cos(el.O),sO=Math.sin(el.O),cu=Math.cos(u),su=Math.sin(u),ci=Math.cos(el.i),si=Math.sin(el.i);return new THREE.Vector3(r*(cO*cu-sO*su*ci),r*(su*si),r*(sO*cu+cO*su*ci)).multiplyScalar(SCALE)}
function orbitState(t){const el=elements(t),M=el.n*t,E=solveKepler(M,el.e),f=2*Math.atan2(Math.sqrt(1+el.e)*Math.sin(E/2),Math.sqrt(1-el.e)*Math.cos(E/2)),pos=eciFromTrue(f,el),pos2=eciFromTrue(f+1e-4,el),vel=pos2.sub(pos).normalize(),r=el.a*(1-el.e*Math.cos(E));return{el,f,pos,vel,r,alt:r-RE,speed:Math.sqrt(MU*(2/r-1/el.a))}}
function rebuildOrbit(){const el=elements(state.simTime),pts=[];for(let n=0;n<=384;n++)pts.push(eciFromTrue(n/384*TAU,el));orbitLine.geometry.dispose();orbitLine.geometry=new THREE.BufferGeometry().setFromPoints(pts)}
function intersectEllipsoid(origin,dir){const a=VIS_RE,b=VIS_RE*FLAT,A=(dir.x*dir.x+dir.z*dir.z)/(a*a)+dir.y*dir.y/(b*b),B=2*((origin.x*dir.x+origin.z*dir.z)/(a*a)+origin.y*dir.y/(b*b)),C=(origin.x*origin.x+origin.z*origin.z)/(a*a)+origin.y*origin.y/(b*b)-1,D=B*B-4*A*C;if(D<0)return null;const s=Math.sqrt(D),t1=(-B-s)/(2*A),t2=(-B+s)/(2*A),t=t1>0?t1:t2>0?t2:null;return t?origin.clone().addScaledVector(dir,t):null}
function sensorHit(os,lookDeg){const nadir=os.pos.clone().negate().normalize(),cross=new THREE.Vector3().crossVectors(os.pos,os.vel).normalize(),l=rad(lookDeg),dir=nadir.multiplyScalar(Math.cos(l)).add(cross.multiplyScalar(Math.sin(l))).normalize();return intersectEllipsoid(os.pos,dir)}
function geodetic(ecef){const lon=Math.atan2(ecef.z,ecef.x),p=Math.hypot(ecef.x,ecef.z),e2=1-(RP*RP)/(RE*RE),lat=Math.atan2(ecef.y,p*(1-e2));return{lat,lon}}
function ecefFromWorld(world,angle){return world.clone().applyAxisAngle(new THREE.Vector3(0,1,0),-angle)}
function surfaceNormal(world){return new THREE.Vector3(world.x/(VIS_RE*VIS_RE),world.y/((VIS_RE*FLAT)**2),world.z/(VIS_RE*VIS_RE)).normalize()}
function sensorGeometry(os,hit,angle){if(!hit)return null;const fov=+$('fov').value,look=+$('look').value,h1=sensorHit(os,look-fov/2),h2=sensorHit(os,look+fov/2),dist=os.pos.distanceTo(hit),radius=h1&&h2?h1.distanceTo(h2)/2:Math.tan(rad(fov/2))*dist,normal=surfaceNormal(hit);cone.visible=state.footprint;footprint.visible=state.footprint;cone.position.copy(os.pos).lerp(hit,.5);cone.scale.set(radius,radius,dist);cone.quaternion.setFromUnitVectors(new THREE.Vector3(0,-1,0),hit.clone().sub(os.pos).normalize());footprint.position.copy(hit).addScaledVector(normal,.012);footprint.scale.setScalar(Math.max(.006,radius));footprint.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);const e1=h1?ecefFromWorld(h1,angle):null,e2=h2?ecefFromWorld(h2,angle):null,swath=e1&&e2?RE*Math.acos(clamp(e1.clone().normalize().dot(e2.clone().normalize()),-1,1)):2*(os.alt)*Math.tan(rad(fov/2));return{swath,radius}}

function paintHit(hitWorld,angle,swath){if(!state.scan||!hitWorld)return;const ecef=ecefFromWorld(hitWorld,angle),geo=geodetic(ecef),u=(geo.lon+Math.PI)/TAU,v=.5-geo.lat/Math.PI,x=u*scanCanvas.width,y=v*scanCanvas.height,px=Math.max(1.8,swath/(TAU*RE)*scanCanvas.width),color=$('sensor').value==='sar'?'rgba(255,196,80,.48)':$('sensor').value==='thermal'?'rgba(255,92,112,.5)':$('sensor').value==='lidar'?'rgba(85,231,255,.62)':'rgba(80,255,173,.48)';sx.save();sx.strokeStyle=color;sx.fillStyle=color;sx.lineWidth=Math.max(2,px*1.75);sx.lineCap='round';sx.shadowColor=color;sx.shadowBlur=7;if(state.lastScan){let lx=state.lastScan.x,ly=state.lastScan.y,dx=x-lx;if(Math.abs(dx)>scanCanvas.width/2){if(dx>0)lx+=scanCanvas.width;else x+=scanCanvas.width}sx.beginPath();sx.moveTo(lx,ly);sx.lineTo(x,y);sx.stroke();sx.beginPath();sx.moveTo(lx-scanCanvas.width,ly);sx.lineTo(x-scanCanvas.width,y);sx.stroke();sx.beginPath();sx.moveTo(lx+scanCanvas.width,ly);sx.lineTo(x+scanCanvas.width,y);sx.stroke()}else{sx.beginPath();sx.arc(x,y,px,0,TAU);sx.fill()}sx.restore();state.lastScan={x:(x+scanCanvas.width)%scanCanvas.width,y};scanTex.needsUpdate=true;const cc=Math.floor(u*cols)%cols,rr=clamp(Math.floor(v*rows),0,rows-1),cr=Math.max(1,Math.ceil(swath/(TAU*RE)*cols));for(let r=-cr;r<=cr;r++)for(let c=-cr;c<=cr;c++){const tr=rr+r;if(tr<0||tr>=rows)continue;const tc=(cc+c+cols)%cols,idx=tr*cols+tc;if(!coverageGrid[idx]){coverageGrid[idx]=1;coveredWeight+=rowWeights[tr]}}if(trackPoints.length===0||trackPoints[trackPoints.length-1].distanceTo(ecef)>.012){trackPoints.push(ecef.clone().normalize().multiply(new THREE.Vector3(5.078,5.078*FLAT,5.078)));if(trackPoints.length>900)trackPoints.shift()}}
function clearCoverage(){sx.clearRect(0,0,scanCanvas.width,scanCanvas.height);scanTex.needsUpdate=true;coverageGrid.fill(0);coveredWeight=0;trackPoints=[];state.lastScan=null;trackLine.geometry.dispose();trackLine.geometry=new THREE.BufferGeometry();toast('Mapa y rastro reiniciados')}
function coverageUI(){const pct=coveredWeight/totalWeight*100;$('coverage').textContent=pct.toFixed(2)+'%';$('coverageBar').style.width=Math.min(100,pct)+'%';$('area').textContent=Math.round(510072000*pct/100).toLocaleString('es-ES')+' km²'}
function formatTime(sec){sec=Math.floor(sec);return`${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec%3600/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function sensorResolution(){return{multi:'10 m',sar:'5 m',lidar:'0,3 m',thermal:'100 m'}[$('sensor').value]}
function updateLabels(os=null,geo=null,swath=null){const el=elements(),w=warpValues[state.warpIndex],current=os||orbitState(state.simTime),h=current.alt;$('altOut').textContent=(+$('altitude').value).toLocaleString('es-ES')+' km';$('eccOut').textContent=(+$('eccentricity').value).toFixed(3);$('incOut').textContent=(+$('inclination').value).toFixed(1)+'°';$('raanOut').textContent=$('raan').value+'°';$('argOut').textContent=$('argPerigee').value+'°';$('fovOut').textContent=$('fov').value+'°';$('lookOut').textContent=$('look').value+'°';$('reliefOut').textContent='×'+$('relief').value;$('warpOut').textContent=w?'×'+w:'PAUSA';$('simRatio').textContent=w?`1 s = ${w<60?w+' s':w/60+' min'}`:'Simulación detenida';$('velocity').textContent=current.speed.toFixed(2)+' km/s';$('velocityKmh').textContent=Math.round(current.speed*3600).toLocaleString('es-ES')+' km/h';$('period').textContent=(TAU/el.n/60).toFixed(1)+' min';$('currentAlt').textContent=Math.round(h).toLocaleString('es-ES')+' km';$('apsides').textContent=Math.round(el.rp-RE).toLocaleString('es-ES')+' / '+Math.round(el.ra-RE).toLocaleString('es-ES')+' km';$('gravity').textContent=(MU/(current.r*current.r)*1000).toFixed(2)+' m/s²';if(geo){$('latitude').textContent=Math.abs(deg(geo.lat)).toFixed(2)+'° '+(geo.lat>=0?'N':'S');$('longitude').textContent=Math.abs(deg(geo.lon)).toFixed(2)+'° '+(geo.lon>=0?'E':'O')}if(swath!==null){$('swathOut').textContent=Math.round(swath).toLocaleString('es-ES')+' km DE FRANJA';$('swathMetric').textContent=Math.round(swath).toLocaleString('es-ES')+' km'}$('resolution').textContent=sensorResolution();$('sensorBand').textContent={multi:'MULTIESPECTRAL',sar:'MICROONDAS · SAR',lidar:'LÁSER · 1064 nm',thermal:'TÉRMICO · 10.8 μm'}[$('sensor').value];$('orbitClass').textContent=el.ra-RE<3000?'LEO'+(el.i>rad(95)&&el.i<rad(105)?' / RETRÓGRADA':''):'MEO';document.querySelectorAll('input[type=range]').forEach(x=>x.style.setProperty('--fill',((x.value-x.min)/(x.max-x.min)*100)+'%'))}
function setRelief(){const physical=.00696*(+$('relief').value);earthMat.displacementScale=physical;earthMat.bumpScale=.009*(+$('relief').value);nightUniforms.dispScale.value=physical;const shell=VIS_RE+physical+.018;scanSphere.geometry.dispose();scanSphere.geometry=new THREE.SphereGeometry(shell,192,108);scanSphere.scale.y=FLAT;clouds.geometry.dispose();clouds.geometry=new THREE.SphereGeometry(shell+.035,192,108);clouds.scale.y=FLAT;updateLabels()}
function cameraUpdate(os,hit,dt,sunDir){if(state.camera==='follow'){const desired=os.pos.clone().add(os.pos.clone().normalize().multiplyScalar(1.2)).add(os.vel.clone().multiplyScalar(-1.2));camera.position.lerp(desired,1-Math.pow(.02,dt));controls.target.lerp(os.pos,.08)}else if(state.camera==='sensor'&&hit){camera.position.lerp(os.pos.clone().add(os.pos.clone().normalize().multiplyScalar(.16)),.09);controls.target.lerp(hit,.12)}else if(state.camera==='terminator'){let side=new THREE.Vector3().crossVectors(sunDir,new THREE.Vector3(0,1,0));if(side.lengthSq()<.01)side.set(1,0,0);side.normalize().multiplyScalar(13).add(new THREE.Vector3(0,1.4,0));camera.position.lerp(side,.04);controls.target.lerp(new THREE.Vector3(),.05)}}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1900)}

let previous=performance.now(),frames=0;
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-previous)/1000);previous=now;const simDelta=dt*(state.running?warpValues[state.warpIndex]:0),oldTime=state.simTime;state.simTime+=simDelta;const date=new Date(START+state.simTime*1000),sunDir=sunVector(date);sunLight.position.copy(sunDir).multiplyScalar(55);sunSprite.position.copy(sunDir).multiplyScalar(78);nightUniforms.sunDirection.value.copy(sunDir);atmoMat.uniforms.sunDirection.value.copy(sunDir);if(state.rotation)state.earthAngle=-gmst(date);earthGroup.rotation.y=state.earthAngle;clouds.rotation.y=state.simTime/EARTH_DAY*TAU*.035;
 const samples=state.scan&&simDelta>0?clamp(Math.ceil(simDelta/4),1,70):1;let os,hit,sg,geo;for(let k=1;k<=samples;k++){const st=oldTime+(state.simTime-oldTime)*k/samples,sd=new Date(START+st*1000),ang=state.rotation?-gmst(sd):state.earthAngle;os=orbitState(st);hit=sensorHit(os,+$('look').value);sg=sensorGeometry(os,hit,ang);if(hit){geo=geodetic(ecefFromWorld(hit,ang));if(state.scan)paintHit(hit,ang,sg.swath)}}
 os=orbitState(state.simTime);hit=sensorHit(os,+$('look').value);sg=sensorGeometry(os,hit,state.earthAngle);if(hit)geo=geodetic(ecefFromWorld(hit,state.earthAngle));sat.position.copy(os.pos);sat.lookAt(hit||new THREE.Vector3());sat.scale.setScalar($('scaleToggle').classList.contains('on')?.78:.000008);if(frames++%10===0){trackLine.geometry.dispose();trackLine.geometry=new THREE.BufferGeometry().setFromPoints(trackPoints);coverageUI();updateLabels(os,geo,sg?sg.swath:null);$('utc').textContent='UTC '+date.toISOString().replace('T',' ').slice(0,19);$('elapsed').textContent='T+ '+formatTime(state.simTime);$('scrub').value=wrap(os.el.n*state.simTime)/TAU*100;if(frames%100===0)rebuildOrbit()}orbitLine.visible=$('orbitToggle').classList.contains('on');trackLine.visible=$('trackToggle').classList.contains('on');clouds.visible=$('cloudToggle').classList.contains('on');atmosphere.visible=$('atmoToggle').classList.contains('on');cameraUpdate(os,hit,dt,sunDir);controls.update();renderer.render(scene,camera)}

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tabpane').forEach(x=>x.classList.toggle('hidden',x.dataset.pane!==b.dataset.tab))});
document.querySelectorAll('.switch').forEach(s=>s.onclick=()=>{s.classList.toggle('on');if(s.id==='earthRotation')state.rotation=s.classList.contains('on');if(s.id==='scanToggle'){state.scan=s.classList.contains('on');state.lastScan=null}if(s.id==='footprintToggle')state.footprint=s.classList.contains('on');if(s.id==='j2Toggle')rebuildOrbit()});
const presets={sentinel:[786,.00012,98.62,18,90,20],landsat:[705,.0012,98.2,92,90,15],iss:[413,.0006,51.64,40,245,28],equatorial:[550,.003,0,0,0,22]};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=presets[b.dataset.preset];$('altitude').value=p[0];$('eccentricity').value=p[1];$('inclination').value=p[2];$('raan').value=p[3];$('argPerigee').value=p[4];$('fov').value=p[5];document.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('active',x===b));trackPoints=[];state.lastScan=null;rebuildOrbit();updateLabels();toast('Elementos orbitales cargados')});
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{state.camera=b.dataset.camera;$('cameraMode').textContent=b.textContent.toUpperCase();document.querySelectorAll('[data-camera]').forEach(x=>x.classList.toggle('active',x===b));if(state.camera==='global'){camera.position.set(12,6.8,12.5);controls.target.set(0,0,0)}toast('Cámara: '+b.textContent)});
['altitude','eccentricity','inclination','raan','argPerigee','fov','look','warp','sensor'].forEach(id=>$(id).addEventListener('input',()=>{if(id==='warp'){state.warpIndex=+$('warp').value;state.running=state.warpIndex>0;$('play').classList.toggle('paused',state.running)}if(['altitude','eccentricity','inclination','raan','argPerigee'].includes(id)){trackPoints=[];state.lastScan=null;rebuildOrbit()}updateLabels()}));
$('relief').addEventListener('input',setRelief);$('clearScan').onclick=clearCoverage;
$('play').onclick=()=>{state.running=!state.running;$('play').classList.toggle('paused',state.running);toast(state.running?'Simulación reanudada':'Simulación en pausa')};document.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>{state.warpIndex=+b.dataset.w;state.running=state.warpIndex>0;$('warp').value=state.warpIndex;document.querySelectorAll('[data-w]').forEach(x=>x.classList.toggle('active',x===b));$('play').classList.toggle('paused',state.running);updateLabels()});
$('menu').onclick=()=>$('controlPanel').classList.toggle('open');$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
state.earthAngle=-gmst(new Date(START));setRelief();rebuildOrbit();updateLabels();requestAnimationFrame(animate);setTimeout(()=>{if(!$('loader').classList.contains('hide'))$('loader').classList.add('hide')},8000);
})();
