(()=>{'use strict';
const TAU=Math.PI*2,VIS_R=5,MAX_TRACK=420,Y=new THREE.Vector3(0,1,0),$=id=>document.getElementById(id),rad=d=>d*Math.PI/180,deg=r=>r*180/Math.PI,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),wrap=a=>(a%TAU+TAU)%TAU;
const BASE='https://raw.githubusercontent.com/AlejandroPico/Orbitalis/main/assets/',LC='https://raw.githubusercontent.com/louh/lcars/main/public/planets/',TX='https://raw.githubusercontent.com/ofrohn/threex.planets/master/images/maps/';
const BODIES={
 mercury:{name:'Mercurio',type:'PLANETA TERRESTRE',r:2439.7,polar:2439.7,mu:22032.08,rot:5067030,alt:400,color:LC+'2k_mercury.jpg',height:TX+'mercurybump.jpg',note:'Relieve: mosaico y elevación derivados de MESSENGER/USGS.',atmo:0,glow:0x9ba4a7},
 venus:{name:'Venus',type:'PLANETA TERRESTRE',r:6051.8,polar:6051.8,mu:324858.6,rot:-20996760,alt:500,color:LC+'2k_venus_surface.jpg',height:LC+'2k_venus_surface.jpg',clouds:LC+'2k_venus_atmosphere.jpg',note:'Superficie de radar; relieve visual derivado de la cartografía Magellan.',atmo:.72,glow:0xffb56d},
 earth:{name:'Tierra',type:'PLANETA TERRESTRE',r:6378.137,polar:6356.752,mu:398600.4418,rot:86164.09,alt:700,color:BASE+'earth-blue-marble.jpg',height:BASE+'earth-topology.png',specular:BASE+'earth-water.png',clouds:BASE+'clouds.png',night:BASE+'earth-night.jpg',note:'Topografía global, Blue Marble, nubes y luces nocturnas.',atmo:.48,glow:0x49c9ff},
 moon:{name:'Luna',type:'SATÉLITE ROCOSO',r:1737.4,polar:1735.97,mu:4902.8,rot:2360591,alt:100,color:LC+'2k_moon.jpg',height:TX+'moonbump.jpg',note:'Relieve lunar cartografiado mediante misiones orbitales.',atmo:0,glow:0xaeb9c2},
 mars:{name:'Marte',type:'PLANETA TERRESTRE',r:3396.2,polar:3376.2,mu:42828.37,rot:88642.7,alt:400,color:LC+'2k_mars.jpg',height:TX+'marsbump.jpg',note:'Mosaico global y altimetría basada en cartografía marciana.',atmo:.22,glow:0xff704f},
 jupiter:{name:'Júpiter',type:'GIGANTE GASEOSO',r:71492,polar:66854,mu:126686534,rot:35730,alt:6000,color:LC+'2k_jupiter.jpg',note:'No existe superficie sólida: se cartografía estructura nubosa.',atmo:.2,glow:0xffc591,gas:true},
 saturn:{name:'Saturno',type:'GIGANTE GASEOSO',r:60268,polar:54364,mu:37931187,rot:38362,alt:6000,color:LC+'2k_saturn.jpg',ring:LC+'2k_saturn_ring_alpha.png',note:'No existe superficie sólida: se cartografía estructura nubosa.',atmo:.18,glow:0xffd7a2,gas:true},
 uranus:{name:'Urano',type:'GIGANTE DE HIELO',r:25559,polar:24973,mu:5793939,rot:-62064,alt:3500,color:LC+'2k_uranus.jpg',note:'Cartografía de capas nubosas; no representa terreno sólido.',atmo:.35,glow:0x86eaff,gas:true},
 neptune:{name:'Neptuno',type:'GIGANTE DE HIELO',r:24764,polar:24341,mu:6836529,rot:57996,alt:3500,color:LC+'2k_neptune.jpg',note:'Cartografía de capas nubosas; no representa terreno sólido.',atmo:.38,glow:0x477cff,gas:true},
 pluto:{name:'Plutón',type:'PLANETA ENANO',r:1188.3,polar:1188.3,mu:869.6,rot:551856,alt:100,color:TX+'plutomap.jpg',height:TX+'plutomap.jpg',note:'Mosaico New Horizons; las regiones no observadas quedan identificables.',atmo:.06,glow:0x9cbcff}
};
const state={body:'earth',time:0,running:true,speed:100,scan:true,beam:true,mapMode:'relief',camera:'global',textureDirty:false,mapDirty:true,lastUpload:0,lastMapDraw:0,lastTelemetry:0,bodyAngle:0};
const records={};
function record(key){if(records[key])return records[key];const scan=document.createElement('canvas'),mask=document.createElement('canvas');scan.width=mask.width=1024;scan.height=mask.height=512;return records[key]={scan,sc:scan.getContext('2d'),mask,mc:mask.getContext('2d'),last:null,covered:new Uint8Array(360*180),coveredWeight:0,track:[],color:null,relief:null}}

const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.01,300),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});camera.position.set(13,6.5,13);renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.86;$('scene').appendChild(renderer.domElement);
const controls=new THREE.OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=5.2;controls.maxDistance=45;controls.enablePan=false;
const texLoader=new THREE.TextureLoader(),texCache={};texLoader.setCrossOrigin('anonymous');
function tex(file,srgb=true){if(!file)return null;if(texCache[file])return texCache[file];const t=texLoader.load(file,()=>{},undefined,()=>showLoadError());t.anisotropy=renderer.capabilities.getMaxAnisotropy();if(srgb)t.encoding=THREE.sRGBEncoding;return texCache[file]=t}
const sky=texLoader.load(BASE+'night-sky.png',()=>{},undefined,showLoadError);sky.mapping=THREE.EquirectangularReflectionMapping;sky.encoding=THREE.sRGBEncoding;scene.background=sky;
scene.add(new THREE.AmbientLight(0x24394a,.2));const sunDir=new THREE.Vector3(1,.18,.36).normalize(),sun=new THREE.DirectionalLight(0xfff0d2,1.65);sun.position.copy(sunDir).multiplyScalar(50);scene.add(sun);
const sunSprite=(()=>{const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),g=x.createRadialGradient(128,128,1,128,128,127);g.addColorStop(0,'#fff');g.addColorStop(.06,'#fff0b5');g.addColorStop(.2,'rgba(255,166,55,.32)');g.addColorStop(1,'rgba(255,120,20,0)');x.fillStyle=g;x.fillRect(0,0,256,256);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));s.position.copy(sunDir).multiplyScalar(80);s.scale.set(10,10,1);scene.add(s);return s})();

const bodyGroup=new THREE.Group();scene.add(bodyGroup);let globe,clouds,atmosphere,rings,nightLayer,scanShell,scanTexture,currentMat;
const sat=makeSatellite();scene.add(sat);const orbitLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0x62e9ff,transparent:true,opacity:.5}));scene.add(orbitLine);
const trackPositions=new Float32Array(MAX_TRACK*3),trackGeometry=new THREE.BufferGeometry();trackGeometry.setAttribute('position',new THREE.BufferAttribute(trackPositions,3).setUsage(THREE.DynamicDrawUsage));trackGeometry.setDrawRange(0,0);const trackLine=new THREE.Line(trackGeometry,new THREE.LineBasicMaterial({color:0x6dffad,transparent:true,opacity:.75}));bodyGroup.add(trackLine);
const cone=new THREE.Mesh(new THREE.ConeGeometry(1,1,48,1,true),new THREE.MeshBasicMaterial({color:0x55efff,transparent:true,opacity:.15,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));scene.add(cone);
const footprint=new THREE.Mesh(new THREE.RingGeometry(.82,1,72),new THREE.MeshBasicMaterial({color:0x72ffb0,transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false}));scene.add(footprint);

function makeSatellite(){const g=new THREE.Group(),gold=new THREE.MeshStandardMaterial({color:0xcaa55a,metalness:.9,roughness:.2}),blue=new THREE.MeshStandardMaterial({color:0x12467e,metalness:.65,roughness:.2,emissive:0x072c55,emissiveIntensity:.7}),black=new THREE.MeshStandardMaterial({color:0x03080c,metalness:.7});const body=new THREE.Mesh(new THREE.BoxGeometry(.16,.2,.28),gold),sensor=new THREE.Mesh(new THREE.CylinderGeometry(.055,.085,.12,20),black);sensor.rotation.x=Math.PI/2;sensor.position.z=.19;const pg=new THREE.BoxGeometry(.52,.012,.16),a=new THREE.Mesh(pg,blue),b=a.clone();a.position.x=.34;b.position.x=-.34;g.add(body,sensor,a,b);g.add(new THREE.PointLight(0x5aeaff,.7,1.8));return g}
function atmosphereMaterial(color,strength){return new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,blending:THREE.AdditiveBlending,depthWrite:false,uniforms:{color:{value:new THREE.Color(color)},strength:{value:strength},sun:{value:sunDir}},vertexShader:'varying vec3 n;varying vec3 p;void main(){n=normalize(mat3(modelMatrix)*normal);vec4 w=modelMatrix*vec4(position,1.);p=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}',fragmentShader:'uniform vec3 color;uniform float strength;uniform vec3 sun;varying vec3 n;varying vec3 p;void main(){float rim=pow(1.0-clamp(dot(n,normalize(cameraPosition-p)),0.0,1.0),3.0);float day=.25+.75*smoothstep(-.4,.2,dot(n,sun));gl_FragColor=vec4(color,rim*day*strength);}'})}
function removeObject(o){if(!o)return;bodyGroup.remove(o);if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose()}
function loadImage(file){return new Promise((resolve,reject)=>{if(!file){resolve(null);return}const i=new Image();i.crossOrigin='anonymous';i.onload=()=>resolve(i);i.onerror=reject;i.src=file})}
async function buildBody(key){state.body=key;const b=BODIES[key],rec=record(key);$('loadStatus').textContent='Cargando '+b.name+'…';$('loader').classList.remove('hide');[globe,clouds,atmosphere,rings,nightLayer,scanShell].forEach(removeObject);globe=clouds=atmosphere=rings=nightLayer=scanShell=null;
 const height=tex(b.height,false),relief=+$('relief').value,disp=b.height?.0065*relief:0;currentMat=new THREE.MeshPhongMaterial({map:tex(b.color),bumpMap:height,bumpScale:b.height?.012*relief:0,displacementMap:height,displacementScale:disp,specularMap:tex(b.specular,false),specular:new THREE.Color(b.specular?0x456778:0x07090a),shininess:b.specular?28:3});globe=new THREE.Mesh(new THREE.SphereGeometry(VIS_R,192,112),currentMat);globe.scale.y=b.polar/b.r;bodyGroup.add(globe);if(b.night){const nm=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{lights:{value:tex(b.night)},sun:{value:sunDir}},vertexShader:'varying vec2 u;varying vec3 n;void main(){u=uv;n=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform sampler2D lights;uniform vec3 sun;varying vec2 u;varying vec3 n;void main(){vec3 c=texture2D(lights,u).rgb;float l=smoothstep(.58,.92,max(c.r,max(c.g,c.b)));float dark=smoothstep(.04,-.18,dot(n,sun));vec3 city=pow(c,vec3(2.2))*vec3(1.25,.92,.58);gl_FragColor=vec4(city,l*dark*.72);}'});nightLayer=new THREE.Mesh(new THREE.SphereGeometry(VIS_R+disp+.006,144,80),nm);nightLayer.scale.y=b.polar/b.r;bodyGroup.add(nightLayer)}
 if(b.clouds){clouds=new THREE.Mesh(new THREE.SphereGeometry(VIS_R+disp+.035,160,92),new THREE.MeshPhongMaterial({map:tex(b.clouds),transparent:true,opacity:key==='venus'?.76:.38,depthWrite:false}));clouds.scale.y=b.polar/b.r;bodyGroup.add(clouds)}
 if(b.atmo){atmosphere=new THREE.Mesh(new THREE.SphereGeometry(VIS_R+Math.max(.11,b.atmo*.23),112,72),atmosphereMaterial(b.glow,b.atmo));atmosphere.scale.y=b.polar/b.r;bodyGroup.add(atmosphere)}
 if(b.ring){rings=new THREE.Mesh(new THREE.RingGeometry(6.1,10.8,160),new THREE.MeshBasicMaterial({map:tex(b.ring),transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false}));rings.rotation.x=Math.PI/2;bodyGroup.add(rings)}
 scanTexture=new THREE.CanvasTexture(rec.scan);scanTexture.minFilter=THREE.LinearFilter;scanShell=new THREE.Mesh(new THREE.SphereGeometry(VIS_R+disp+.018,144,80),new THREE.MeshBasicMaterial({map:scanTexture,transparent:true,opacity:.72,depthWrite:false,blending:THREE.AdditiveBlending}));scanShell.scale.y=b.polar/b.r;bodyGroup.add(scanShell);
 try{[rec.color,rec.relief]=await Promise.all([rec.color||loadImage(b.color),rec.relief||loadImage(b.height||b.color)])}catch(e){showLoadError();return}
 const altMax=Math.max(500,Math.round(b.r*.55/100)*100);$('altitude').min=Math.max(20,Math.round(b.r*.02/10)*10);$('altitude').max=altMax;$('altitude').step=Math.max(1,Math.round(b.r/500));$('altitude').value=b.alt;$('worldName').textContent=b.name.toUpperCase();$('worldType').textContent=b.type;$('tBody').textContent=b.name;$('dataNote').textContent=b.note;state.lastMapDraw=0;state.mapDirty=true;state.textureDirty=true;state.bodyAngle=0;state.time=0;rec.last=null;updateTrack();rebuildOrbit();updateLabels();setMapMode(state.mapMode);$('loader').classList.add('hide')}

function elements(t){const b=BODIES[state.body],e=+$('eccentricity').value,rp=b.r+(+$('altitude').value),a=rp/(1-e),p=a*(1-e*e),n=Math.sqrt(b.mu/(a*a*a)),i=rad(+$('inclination').value),O=rad(+$('raan').value);return{b,e,rp,a,p,n,i,O}}
function solveE(M,e){M=wrap(M);let E=M;for(let k=0;k<7;k++)E-=(E-e*Math.sin(E)-M)/(1-e*Math.cos(E));return E}
function positionAt(t,trueAnomaly=null){const el=elements(t);let f=trueAnomaly,r;if(f===null){const E=solveE(el.n*t,el.e);f=2*Math.atan2(Math.sqrt(1+el.e)*Math.sin(E/2),Math.sqrt(1-el.e)*Math.cos(E/2));r=el.a*(1-el.e*Math.cos(E))}else r=el.p/(1+el.e*Math.cos(f));const cO=Math.cos(el.O),sO=Math.sin(el.O),cf=Math.cos(f),sf=Math.sin(f),ci=Math.cos(el.i),si=Math.sin(el.i),scale=VIS_R/el.b.r;return{el,r,f,pos:new THREE.Vector3(r*(cO*cf-sO*sf*ci),r*(sf*si),r*(sO*cf+cO*sf*ci)).multiplyScalar(scale)}}
function orbitState(t){const o=positionAt(t),p2=positionAt(t+.05).pos,vel=p2.sub(o.pos).normalize(),speed=Math.sqrt(o.el.b.mu*(2/o.r-1/o.el.a));return{...o,vel,speed,alt:o.r-o.el.b.r}}
function rebuildOrbit(){const pts=[];for(let k=0;k<=256;k++)pts.push(positionAt(state.time,k/256*TAU).pos);orbitLine.geometry.dispose();orbitLine.geometry=new THREE.BufferGeometry().setFromPoints(pts)}
function intersect(os,dir){const b=BODIES[state.body],a=VIS_R,c=VIS_R*b.polar/b.r,A=(dir.x*dir.x+dir.z*dir.z)/(a*a)+dir.y*dir.y/(c*c),B=2*((os.pos.x*dir.x+os.pos.z*dir.z)/(a*a)+os.pos.y*dir.y/(c*c)),C=(os.pos.x*os.pos.x+os.pos.z*os.pos.z)/(a*a)+os.pos.y*os.pos.y/(c*c)-1,D=B*B-4*A*C;if(D<0)return null;const q=(-B-Math.sqrt(D))/(2*A);return q>0?os.pos.clone().addScaledVector(dir,q):null}
function hitAt(os,look){const nadir=os.pos.clone().negate().normalize(),cross=new THREE.Vector3().crossVectors(os.pos,os.vel).normalize(),l=rad(look),dir=nadir.multiplyScalar(Math.cos(l)).add(cross.multiplyScalar(Math.sin(l))).normalize();return intersect(os,dir)}
function toLocal(world,angle){return world.clone().applyAxisAngle(Y,-angle)}
function geo(local){const b=BODIES[state.body],lon=Math.atan2(local.z,local.x),p=Math.hypot(local.x,local.z),e2=1-(b.polar*b.polar)/(b.r*b.r),lat=Math.atan2(local.y,p*(1-e2));return{lat,lon}}
function sensorView(os,hit){if(!hit)return null;const fov=+$('fov').value,look=+$('look').value,h1=hitAt(os,look-fov/2),h2=hitAt(os,look+fov/2),dist=os.pos.distanceTo(hit),radius=h1&&h2?h1.distanceTo(h2)/2:dist*Math.tan(rad(fov/2)),normal=new THREE.Vector3(hit.x/(VIS_R*VIS_R),hit.y/((VIS_R*BODIES[state.body].polar/BODIES[state.body].r)**2),hit.z/(VIS_R*VIS_R)).normalize();cone.visible=state.beam;footprint.visible=state.beam;cone.position.copy(os.pos).lerp(hit,.5);cone.scale.set(radius,dist,radius);cone.quaternion.setFromUnitVectors(new THREE.Vector3(0,-1,0),hit.clone().sub(os.pos).normalize());footprint.position.copy(hit).addScaledVector(normal,.012);footprint.scale.setScalar(radius);footprint.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);const swath=h1&&h2?BODIES[state.body].r*Math.acos(clamp(toLocal(h1,state.bodyAngle).normalize().dot(toLocal(h2,state.bodyAngle).normalize()),-1,1)):2*os.alt*Math.tan(rad(fov/2));return{swath,radius}}
function paint(world,angle,swath){if(!state.scan||!world)return;const rec=record(state.body),g=geo(toLocal(world,angle)),x=(g.lon+Math.PI)/TAU*1024,y=(.5-g.lat/Math.PI)*512,px=Math.max(1.2,swath/(TAU*BODIES[state.body].r)*1024);drawPath(rec.sc,rec.last,x,y,px,'rgba(82,255,172,.52)',true);drawPath(rec.mc,rec.last,x,y,px,'#fff',false);rec.last={x:(x+1024)%1024,y};state.textureDirty=state.mapDirty=true;const col=Math.floor((g.lon+Math.PI)/TAU*360)%360,row=clamp(Math.floor((.5-g.lat/Math.PI)*180),0,179),cr=Math.max(1,Math.ceil(swath/(TAU*BODIES[state.body].r)*360));for(let rr=-cr;rr<=cr;rr++)for(let cc=-cr;cc<=cr;cc++){const tr=row+rr;if(tr<0||tr>=180)continue;const tc=(col+cc+360)%360,idx=tr*360+tc;if(!rec.covered[idx]){rec.covered[idx]=1;rec.coveredWeight+=Math.cos(((tr+.5)/180-.5)*Math.PI)}}const local=toLocal(world,angle).normalize().multiply(new THREE.Vector3(5.025,5.025*BODIES[state.body].polar/BODIES[state.body].r,5.025));if(!rec.track.length||rec.track[rec.track.length-1].distanceTo(local)>.025){rec.track.push(local);if(rec.track.length>MAX_TRACK)rec.track.shift()}}
function drawPath(ctx,last,x,y,width,color,glow){ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=Math.max(2,width*1.65);ctx.lineCap='round';if(glow){ctx.shadowColor=color;ctx.shadowBlur=3}if(last){let lx=last.x,xx=x;if(Math.abs(xx-lx)>512){if(xx>lx)lx+=1024;else xx+=1024}for(const off of [-1024,0,1024]){ctx.beginPath();ctx.moveTo(lx+off,last.y);ctx.lineTo(xx+off,y);ctx.stroke()}}else{ctx.beginPath();ctx.arc(x,y,width,0,TAU);ctx.fill()}ctx.restore()}
function updateTrack(){const tr=record(state.body).track,n=tr.length;for(let i=0;i<n;i++){trackPositions[i*3]=tr[i].x;trackPositions[i*3+1]=tr[i].y;trackPositions[i*3+2]=tr[i].z}trackGeometry.attributes.position.needsUpdate=true;trackGeometry.setDrawRange(0,n)}
function coverage(){const rec=record(state.body),total=360*180*2/Math.PI;return clamp(rec.coveredWeight/total*100,0,100)}
const mapCtx=$('mapCanvas').getContext('2d'),compose=document.createElement('canvas'),composeCtx=compose.getContext('2d');compose.width=1280;compose.height=640;
function redrawMap(){const rec=record(state.body),img=state.mapMode==='visual'?rec.color:rec.relief;if(!img)return;mapCtx.fillStyle='#010407';mapCtx.fillRect(0,0,1280,640);mapCtx.save();mapCtx.globalAlpha=.075;mapCtx.drawImage(img,0,0,1280,640);mapCtx.restore();composeCtx.clearRect(0,0,1280,640);composeCtx.drawImage(img,0,0,1280,640);composeCtx.globalCompositeOperation='destination-in';composeCtx.drawImage(rec.mask,0,0,1280,640);composeCtx.globalCompositeOperation='source-over';mapCtx.drawImage(compose,0,0);state.mapDirty=false}
function resetMap(){const rec=record(state.body);rec.sc.clearRect(0,0,1024,512);rec.mc.clearRect(0,0,1024,512);rec.covered.fill(0);rec.coveredWeight=0;rec.track=[];rec.last=null;state.textureDirty=state.mapDirty=true;updateTrack();toast('Cartografía reiniciada')}
function setMapMode(mode){state.mapMode=mode;document.querySelectorAll('[data-mapmode]').forEach(x=>x.classList.toggle('active',x.dataset.mapmode===mode));const b=BODIES[state.body];$('mapTitle').textContent=b.name.toUpperCase()+' · '+(mode==='relief'?(b.gas?'NUBES':'ALTIMETRÍA'):'VISUAL');$('mapType').textContent=b.gas?'CAPAS NUBOSAS':mode==='relief'?'DEM / TOPOGRAFÍA':'IMAGEN ORBITAL';state.mapDirty=true}
function updateLabels(os=null,g=null,swath=null){const b=BODIES[state.body],el=elements(state.time),pct=coverage(),o=os||orbitState(state.time);$('altitudeOut').textContent=Math.round(+$('altitude').value).toLocaleString('es-ES')+' km';$('eccentricityOut').textContent=(+$('eccentricity').value).toFixed(3);$('inclinationOut').textContent=(+$('inclination').value).toFixed(1)+'°';$('raanOut').textContent=$('raan').value+'°';$('fovOut').textContent=$('fov').value+'°';$('lookOut').textContent=$('look').value+'°';$('reliefOut').textContent='×'+$('relief').value;$('tAltitude').textContent=Math.round(o.alt).toLocaleString('es-ES')+' km';$('tVelocity').textContent=o.speed.toFixed(2)+' km/s';$('tPeriod').textContent=(TAU/el.n/60).toFixed(1)+' min';if(g){$('tCoords').textContent=`${Math.abs(deg(g.lat)).toFixed(1)}°${g.lat>=0?'N':'S'} · ${Math.abs(deg(g.lon)).toFixed(1)}°${g.lon>=0?'E':'O'}`;$('mapCoordinates').textContent=`LAT ${deg(g.lat).toFixed(2)}° · LON ${deg(g.lon).toFixed(2)}°`}$('tSwath').textContent=swath===null?'—':Math.round(swath).toLocaleString('es-ES')+' km';$('tCoverage').textContent=pct.toFixed(2)+'%';$('mapCoverage').textContent=pct.toFixed(2)+'% REVELADO';$('mapProgress').style.width=pct+'%';document.querySelectorAll('input[type=range]').forEach(x=>x.style.setProperty('--fill',((x.value-x.min)/(x.max-x.min)*100)+'%'))}
function showLoadError(){$('loader').classList.add('hide');$('error').classList.remove('hidden')}
function toast(msg){$('loadStatus').textContent=msg}

let last=performance.now(),frame=0;
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.04,(now-last)/1000);last=now;const delta=state.running?dt*state.speed:0,old=state.time;state.time+=delta;const b=BODIES[state.body];state.bodyAngle=wrap(state.bodyAngle+(b.rot?delta/b.rot*TAU:0));bodyGroup.rotation.y=state.bodyAngle;if(clouds)clouds.rotation.y+=dt*(state.body==='venus'?.006:.012);
 const samples=state.scan&&delta>0?clamp(Math.ceil(delta/30),1,6):1;for(let k=1;k<=samples;k++){const t=old+delta*k/samples,angle=wrap(state.bodyAngle-(state.time-t)/b.rot*TAU),os=orbitState(t),hit=hitAt(os,+$('look').value);if(hit)paint(hit,angle,2*os.alt*Math.tan(rad(+$('fov').value/2)))}
 const os=orbitState(state.time),hit=hitAt(os,+$('look').value),sv=sensorView(os,hit),g=hit?geo(toLocal(hit,state.bodyAngle)):null;sat.position.copy(os.pos);sat.lookAt(hit||new THREE.Vector3());sat.scale.setScalar(.78);orbitLine.visible=$('orbitToggle').classList.contains('on');trackLine.visible=$('trackToggle').classList.contains('on');if(clouds)clouds.visible=$('cloudToggle').classList.contains('on');if(atmosphere)atmosphere.visible=$('atmosphereToggle').classList.contains('on');if(state.textureDirty&&now-state.lastUpload>200){scanTexture.needsUpdate=true;state.textureDirty=false;state.lastUpload=now}if(state.mapDirty&&now-state.lastMapDraw>260){redrawMap();state.lastMapDraw=now}if(now-state.lastTelemetry>400){updateTrack();updateLabels(os,g,sv?sv.swath:null);state.lastTelemetry=now}controls.update();renderer.render(scene,camera);frame++}

$('menuButton').onclick=()=>$('drawer').classList.add('open');$('closeDrawer').onclick=()=>$('drawer').classList.remove('open');document.querySelectorAll('[data-body]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-body]').forEach(x=>x.classList.toggle('active',x===btn));buildBody(btn.dataset.body)});
document.querySelectorAll('.switch').forEach(btn=>btn.onclick=()=>{btn.classList.toggle('on');if(btn.id==='scanToggle'){state.scan=btn.classList.contains('on');record(state.body).last=null}if(btn.id==='beamToggle')state.beam=btn.classList.contains('on')});
['altitude','eccentricity','inclination','raan'].forEach(id=>$(id).oninput=()=>{record(state.body).last=null;rebuildOrbit();updateLabels()});['fov','look'].forEach(id=>$(id).oninput=()=>{record(state.body).last=null;updateLabels()});$('relief').oninput=()=>buildBody(state.body);$('resetMap').onclick=resetMap;document.querySelectorAll('[data-mapmode]').forEach(x=>x.onclick=()=>setMapMode(x.dataset.mapmode));$('minimizeMap').onclick=()=>$('mapPanel').classList.toggle('minimized');
$('play').onclick=()=>{state.running=!state.running;$('play').classList.toggle('pause',state.running)};document.querySelectorAll('[data-speed]').forEach(btn=>btn.onclick=()=>{state.speed=+btn.dataset.speed;state.running=true;$('play').classList.add('pause');document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===btn))});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
buildBody('earth').then(()=>requestAnimationFrame(animate));
})();
