(function () {
  const TX =
    "https://raw.githubusercontent.com/ofrohn/threex.planets/master/images/maps/";
  const bodies = {
    ceres: {
      name: "Ceres",
      type: "PLANETA ENANO",
      family: "Cinturón de asteroides",
      r: 469.7,
      polar: 445,
      mu: 62.63,
      rot: 32667,
      alt: 80,
      color: TX + "ceresmap.jpg",
      height: TX + "ceresmap.jpg",
      note: "Cartografía global de Ceres. El relieve visual es aproximado.",
      atmo: 0,
      glow: 0xadb7c2,
    },
    vesta: {
      name: "Vesta",
      type: "ASTEROIDE",
      family: "Cinturón de asteroides",
      r: 262.7,
      polar: 223.2,
      mu: 17.29,
      rot: 19231,
      alt: 60,
      color: TX + "vestamap.jpg",
      height: TX + "vestabump.jpg",
      note: "Mosaico de Vesta y relieve derivado de la misión Dawn.",
      atmo: 0,
      glow: 0xb7a895,
    },
    io: {
      name: "Ío",
      type: "LUNA GALILEANA",
      family: "Sistema de Júpiter",
      r: 1821.6,
      polar: 1815.7,
      mu: 5959.9,
      rot: 152853,
      alt: 150,
      color: TX + "iomap.jpg",
      height: TX + "iomap.jpg",
      note: "Mosaico global de Ío; el relieve se exagera solo para visualización.",
      atmo: 0.025,
      glow: 0xffd36d,
    },
    europa: {
      name: "Europa",
      type: "LUNA GALILEANA",
      family: "Sistema de Júpiter",
      r: 1560.8,
      polar: 1560.3,
      mu: 3202.7,
      rot: 306822,
      alt: 120,
      color: TX + "europamap.jpg",
      height: TX + "europamap.jpg",
      note: "Superficie helada de Europa con lineae y terrenos caóticos.",
      atmo: 0.018,
      glow: 0xb6ddff,
    },
    ganymede: {
      name: "Ganímedes",
      type: "LUNA GALILEANA",
      family: "Sistema de Júpiter",
      r: 2634.1,
      polar: 2632.4,
      mu: 9887.8,
      rot: 618153,
      alt: 180,
      color: TX + "ganymedemap.jpg",
      height: TX + "ganymedemap.jpg",
      note: "Mosaico global de Ganímedes; la mayor luna del Sistema Solar.",
      atmo: 0.015,
      glow: 0xaebccc,
    },
    callisto: {
      name: "Calisto",
      type: "LUNA GALILEANA",
      family: "Sistema de Júpiter",
      r: 2410.3,
      polar: 2409.2,
      mu: 7179.3,
      rot: 1441931,
      alt: 180,
      color: TX + "callistomap.jpg",
      height: TX + "callistomap.jpg",
      note: "Superficie intensamente craterizada de Calisto.",
      atmo: 0.012,
      glow: 0xa6a9ad,
    },
    titan: {
      name: "Titán",
      type: "LUNA CON ATMÓSFERA",
      family: "Sistema de Saturno",
      r: 2574.7,
      polar: 2574.7,
      mu: 8978.1,
      rot: 1377648,
      alt: 300,
      color: TX + "titanmap.jpg",
      height: TX + "titanmap.jpg",
      clouds: TX + "titanclouds.jpg",
      note: "Representación de Titán. Su atmósfera opaca impide observar directamente la superficie en visible.",
      atmo: 0.75,
      glow: 0xffa94f,
    },
    enceladus: {
      name: "Encélado",
      type: "LUNA HELADA",
      family: "Sistema de Saturno",
      r: 252.1,
      polar: 248.3,
      mu: 7.21,
      rot: 118386,
      alt: 45,
      color: TX + "enceladusmap.jpg",
      height: TX + "enceladusmap.jpg",
      note: "Superficie helada de Encélado; mosaico global de resolución desigual.",
      atmo: 0.01,
      glow: 0xd9efff,
    },
    triton: {
      name: "Tritón",
      type: "LUNA HELADA",
      family: "Sistema de Neptuno",
      r: 1353.4,
      polar: 1353.4,
      mu: 1427.6,
      rot: -507773,
      alt: 100,
      color: TX + "tritonmap.jpg",
      height: TX + "tritonmap.jpg",
      note: "Cartografía de Tritón basada principalmente en Voyager 2.",
      atmo: 0.04,
      glow: 0xb7d6ff,
    },
    phobos: {
      name: "Fobos",
      type: "LUNA IRREGULAR",
      family: "Sistema de Marte",
      r: 11.27,
      polar: 9.1,
      mu: 0.000711,
      rot: 27552,
      alt: 3,
      color: TX + "phobosmap.jpg",
      height: TX + "phobosbump.jpg",
      note: "Modelo visual de Fobos. A esta escala el cuerpo real no es esférico.",
      atmo: 0,
      glow: 0x9c8c78,
    },
    deimos: {
      name: "Deimos",
      type: "LUNA IRREGULAR",
      family: "Sistema de Marte",
      r: 6.2,
      polar: 5.2,
      mu: 0.0000985,
      rot: 109123,
      alt: 2,
      color: TX + "deimosmap.jpg",
      height: TX + "deimosmap.jpg",
      note: "Mosaico de Deimos con zonas de menor resolución.",
      atmo: 0,
      glow: 0x9f9588,
    },
    charon: {
      name: "Caronte",
      type: "LUNA DE PLANETA ENANO",
      family: "Sistema de Plutón",
      r: 606,
      polar: 606,
      mu: 105.88,
      rot: 551856,
      alt: 60,
      color: TX + "charonmap.jpg",
      height: TX + "charonmap.jpg",
      note: "Mosaico de Caronte procedente de imágenes de New Horizons.",
      atmo: 0,
      glow: 0xb6a9a2,
    },
  };

  const cities = {
    madrid: { name: "Madrid", region: "Europa", lat: 40.4168, lon: -3.7038 },
    lisbon: { name: "Lisboa", region: "Europa", lat: 38.7223, lon: -9.1393 },
    london: { name: "Londres", region: "Europa", lat: 51.5072, lon: -0.1276 },
    paris: { name: "París", region: "Europa", lat: 48.8566, lon: 2.3522 },
    berlin: { name: "Berlín", region: "Europa", lat: 52.52, lon: 13.405 },
    rome: { name: "Roma", region: "Europa", lat: 41.9028, lon: 12.4964 },
    warsaw: { name: "Varsovia", region: "Europa", lat: 52.2297, lon: 21.0122 },
    moscow: {
      name: "Moscú",
      region: "Europa/Asia",
      lat: 55.7558,
      lon: 37.6173,
    },
    washington: {
      name: "Washington D. C.",
      region: "Norteamérica",
      lat: 38.9072,
      lon: -77.0369,
    },
    newyork: {
      name: "Nueva York",
      region: "Norteamérica",
      lat: 40.7128,
      lon: -74.006,
    },
    mexico: {
      name: "Ciudad de México",
      region: "Norteamérica",
      lat: 19.4326,
      lon: -99.1332,
    },
    losangeles: {
      name: "Los Ángeles",
      region: "Norteamérica",
      lat: 34.0522,
      lon: -118.2437,
    },
    toronto: {
      name: "Toronto",
      region: "Norteamérica",
      lat: 43.6532,
      lon: -79.3832,
    },
    vancouver: {
      name: "Vancouver",
      region: "Norteamérica",
      lat: 49.2827,
      lon: -123.1207,
    },
    bogota: { name: "Bogotá", region: "Sudamérica", lat: 4.711, lon: -74.0721 },
    lima: { name: "Lima", region: "Sudamérica", lat: -12.0464, lon: -77.0428 },
    santiago: {
      name: "Santiago de Chile",
      region: "Sudamérica",
      lat: -33.4489,
      lon: -70.6693,
    },
    buenosaires: {
      name: "Buenos Aires",
      region: "Sudamérica",
      lat: -34.6037,
      lon: -58.3816,
    },
    saopaulo: {
      name: "São Paulo",
      region: "Sudamérica",
      lat: -23.5505,
      lon: -46.6333,
    },
    caracas: {
      name: "Caracas",
      region: "Sudamérica",
      lat: 10.4806,
      lon: -66.9036,
    },
    cairo: { name: "El Cairo", region: "África", lat: 30.0444, lon: 31.2357 },
    casablanca: {
      name: "Casablanca",
      region: "África",
      lat: 33.5731,
      lon: -7.5898,
    },
    lagos: { name: "Lagos", region: "África", lat: 6.5244, lon: 3.3792 },
    nairobi: { name: "Nairobi", region: "África", lat: -1.2921, lon: 36.8219 },
    johannesburg: {
      name: "Johannesburgo",
      region: "África",
      lat: -26.2041,
      lon: 28.0473,
    },
    addis: { name: "Adís Abeba", region: "África", lat: 8.9806, lon: 38.7578 },
    dubai: {
      name: "Dubái",
      region: "Oriente Medio",
      lat: 25.2048,
      lon: 55.2708,
    },
    riyadh: {
      name: "Riad",
      region: "Oriente Medio",
      lat: 24.7136,
      lon: 46.6753,
    },
    istanbul: {
      name: "Estambul",
      region: "Oriente Medio",
      lat: 41.0082,
      lon: 28.9784,
    },
    tehran: {
      name: "Teherán",
      region: "Oriente Medio",
      lat: 35.6892,
      lon: 51.389,
    },
    tokyo: { name: "Tokio", region: "Asia", lat: 35.6762, lon: 139.6503 },
    beijing: { name: "Pekín", region: "Asia", lat: 39.9042, lon: 116.4074 },
    seoul: { name: "Seúl", region: "Asia", lat: 37.5665, lon: 126.978 },
    delhi: { name: "Nueva Delhi", region: "Asia", lat: 28.6139, lon: 77.209 },
    singapore: { name: "Singapur", region: "Asia", lat: 1.3521, lon: 103.8198 },
    jakarta: { name: "Yakarta", region: "Asia", lat: -6.2088, lon: 106.8456 },
    bangkok: { name: "Bangkok", region: "Asia", lat: 13.7563, lon: 100.5018 },
    sydney: { name: "Sídney", region: "Oceanía", lat: -33.8688, lon: 151.2093 },
    melbourne: {
      name: "Melbourne",
      region: "Oceanía",
      lat: -37.8136,
      lon: 144.9631,
    },
    auckland: {
      name: "Auckland",
      region: "Oceanía",
      lat: -36.8509,
      lon: 174.7645,
    },
    honolulu: {
      name: "Honolulu",
      region: "Pacífico",
      lat: 21.3069,
      lon: -157.8583,
    },
  };

  const S = {
    nasa: "https://www.earthdata.nasa.gov/learn/earth-observation-data-basics",
    orbits:
      "https://www.earthdata.nasa.gov/learn/earth-observation-data-basics/orbits",
    spectrum:
      "https://www.earthdata.nasa.gov/learn/earth-observation-data-basics/electromagnetic-spectrum",
    active:
      "https://www.earthdata.nasa.gov/learn/earth-observation-data-basics/remote-sensing/active-instruments",
    passive:
      "https://www.earthdata.nasa.gov/learn/earth-observation-data-basics/remote-sensing/passive-instruments",
    sar: "https://www.earthdata.nasa.gov/learn/earth-observation-data-basics/sar",
    gnss: "https://www.earthdata.nasa.gov/data/space-geodesy-techniques/gnss",
    esa: "https://www.esa.int/Applications/Satellite_navigation/Galileo/What_is_Galileo",
    gps: "https://gssc.esa.int/navipedia/index.php/GPS_General_Introduction",
    moons: "https://science.nasa.gov/solar-system/moons/",
    jmoons: "https://science.nasa.gov/jupiter/jupiter-moons/",
  };
  const chapters = [
    [
      "Fundamentos",
      "Qué es la teledetección",
      [
        "La teledetección obtiene información sin contacto directo. Un sensor orbital registra energía reflejada o emitida y la convierte en medidas calibradas.",
        "El producto final no es una fotografía sin más: contiene valores relacionados con radiancia, temperatura, altura, humedad, rugosidad u otras variables.",
      ],
      [
        "Plataforma, sensor, señal y producto son conceptos distintos.",
        "La resolución siempre implica compromisos.",
      ],
      null,
      S.nasa,
    ],
    [
      "Fundamentos",
      "Gravedad y órbita",
      [
        "Una órbita es una caída libre continua. La gravedad curva la trayectoria mientras la velocidad tangencial evita que el vehículo alcance la superficie.",
        "En el modelo de dos cuerpos la energía y el momento angular permanecen constantes.",
      ],
      [
        "Órbita circular: velocidad constante.",
        "Órbita elíptica: máxima velocidad en el periapsis.",
      ],
      "v = √(μ/r)",
      S.orbits,
    ],
    [
      "Órbitas",
      "Elementos orbitales clásicos",
      [
        "Seis parámetros describen una órbita kepleriana: semieje mayor, excentricidad, inclinación, longitud del nodo ascendente, argumento del periapsis y anomalía.",
        "Modificar RAAN gira el plano alrededor del eje del cuerpo; modificar la inclinación cambia las latitudes alcanzables.",
      ],
      [
        "La excentricidad define la forma.",
        "La anomalía indica la posición dentro de la órbita.",
      ],
      "p = a(1 − e²)",
      S.orbits,
    ],
    [
      "Órbitas",
      "LEO, MEO, GEO y HEO",
      [
        "LEO favorece alta resolución y bajo retardo; MEO se emplea ampliamente en navegación; GEO mantiene aproximadamente la misma longitud terrestre; HEO resulta útil para altas latitudes.",
        "No existe una órbita universalmente mejor: depende de cobertura, potencia, revisitamiento y latencia.",
      ],
      [
        "LEO: aproximadamente 160–2.000 km.",
        "GEO terrestre: aproximadamente 35.786 km de altitud.",
      ],
      null,
      S.orbits,
    ],
    [
      "Órbitas",
      "Órbitas polares y heliosíncronas",
      [
        "Una órbita polar alcanza casi todas las latitudes mientras el planeta rota debajo. Una heliosíncrona mantiene una hora solar local parecida en cada pasada.",
        "Esto mejora la comparación de iluminación entre observaciones realizadas en fechas distintas.",
      ],
      [
        "La inclinación suele ser cercana a 90°.",
        "La precesión nodal puede aprovechar el achatamiento terrestre.",
      ],
      null,
      S.orbits,
    ],
    [
      "Órbitas",
      "Periodo, altura y velocidad",
      [
        "Al aumentar la altura disminuye la velocidad orbital y aumenta el periodo. La zona visible crece, pero la resolución espacial potencial se reduce para una misma óptica.",
        "En cuerpos distintos hay que usar su parámetro gravitacional μ y su radio, no valores terrestres.",
      ],
      ["La escala gráfica del satélite está exagerada para hacerlo visible."],
      "T = 2π√(a³/μ)",
      S.orbits,
    ],
    [
      "Sensores",
      "Espectro electromagnético",
      [
        "Los sensores observan regiones distintas del espectro. Visible, infrarrojo, térmico y microondas responden a propiedades diferentes.",
        "Una composición de falso color asigna bandas invisibles a colores visibles para resaltar fenómenos.",
      ],
      [
        "La atmósfera tiene ventanas de transmisión.",
        "La longitud de onda condiciona interacción y resolución.",
      ],
      "c = λf",
      S.spectrum,
    ],
    [
      "Sensores",
      "Sensores pasivos",
      [
        "Los instrumentos pasivos detectan energía natural reflejada o emitida. Una cámara visible depende del Sol; un radiómetro térmico detecta emisión del propio objeto.",
        "Nubes, iluminación y atmósfera condicionan la observación.",
      ],
      ["Visible y NIR: reflexión solar.", "TIR: emisión térmica."],
      null,
      S.passive,
    ],
    [
      "Sensores",
      "Sensores activos",
      [
        "Radar y lidar emiten pulsos y miden el retorno. Pueden obtener distancia mediante el tiempo de vuelo y propiedades del objetivo mediante intensidad, polarización o forma de onda.",
        "Un radar de microondas puede operar de noche y atravesar muchas nubes.",
      ],
      [
        "El instrumento controla su fuente de energía.",
        "La potencia recibida disminuye fuertemente con la distancia.",
      ],
      "d = c·Δt/2",
      S.active,
    ],
    [
      "Sensores",
      "Radar de apertura sintética",
      [
        "SAR combina coherentemente ecos adquiridos a lo largo de la trayectoria para sintetizar una antena mucho mayor. Produce imágenes de alta resolución independientemente de la luz solar.",
        "La geometría lateral genera efectos como foreshortening, layover y sombra radar.",
      ],
      [
        "La imagen representa retrodispersión, no color visible.",
        "La coherencia permite interferometría.",
      ],
      null,
      S.sar,
    ],
    [
      "Sensores",
      "Lidar y altimetría láser",
      [
        "Un altímetro láser mide tiempos de vuelo muy cortos. Combinado con una órbita precisa permite reconstruir elevación, hielo, vegetación o estructuras.",
        "La huella, frecuencia de pulsos y precisión orbital condicionan el producto final.",
      ],
      [
        "Los fotones recorren ida y vuelta.",
        "Las nubes pueden bloquear el haz.",
      ],
      "h ≈ r_orbital − cΔt/2",
      "https://ilrs.gsfc.nasa.gov/missions/index.html",
    ],
    [
      "Sensores",
      "Altimetría radar oceánica",
      [
        "El radar altimétrico mide la distancia a la superficie marina. Después se aplican correcciones orbitales, atmosféricas, de mareas y geofísicas.",
        "La topografía dinámica del océano permite inferir circulación y variaciones del nivel del mar.",
      ],
      [
        "El mar no es una superficie equipotencial perfecta.",
        "La forma del eco informa sobre oleaje.",
      ],
      null,
      "https://science.nasa.gov/earth/explore/earth-indicators/sea-level/",
    ],
    [
      "Datos",
      "Resolución espacial",
      [
        "La resolución espacial describe el tamaño del elemento de terreno representado por un píxel, pero no equivale automáticamente a precisión.",
        "Una franja más ancha aumenta cobertura y suele reducir detalle para un detector dado.",
      ],
      [
        "GSD y resolución efectiva no siempre coinciden.",
        "La óptica, movimiento y procesado influyen.",
      ],
      "GSD ≈ H·p/f",
      S.nasa,
    ],
    [
      "Datos",
      "Resolución temporal",
      [
        "Es el intervalo entre observaciones de una zona. Depende de la órbita, anchura de franja, capacidad de apuntado y número de satélites.",
        "Una constelación reduce el tiempo de revisita repartiendo planos y fases.",
      ],
      [
        "Revisita no es lo mismo que periodo orbital.",
        "Las nubes reducen revisita útil de sensores ópticos.",
      ],
      null,
      S.nasa,
    ],
    [
      "Datos",
      "Resolución espectral y radiométrica",
      [
        "La resolución espectral describe anchura y número de bandas; la radiométrica, la capacidad de distinguir niveles de señal.",
        "Un sensor hiperespectral ofrece muchas bandas estrechas y permite reconocer firmas de materiales.",
      ],
      [
        "Más bandas generan más datos.",
        "La relación señal/ruido limita la información útil.",
      ],
      "niveles = 2ᵇ",
      S.spectrum,
    ],
    [
      "Datos",
      "De nivel 0 a producto científico",
      [
        "La telemetría cruda debe desempaquetarse, calibrarse y geolocalizarse. Los niveles superiores incorporan correcciones y variables geofísicas.",
        "Una imagen atractiva puede ser un producto derivado; siempre hay que conservar metadatos y trazabilidad.",
      ],
      [
        "L0: datos reconstruidos.",
        "L1: calibrados y geolocalizados.",
        "L2+: variables y composiciones.",
      ],
      null,
      S.nasa,
    ],
    [
      "Cartografía",
      "Coordenadas, datums y proyecciones",
      [
        "Latitud y longitud describen posiciones sobre un modelo del cuerpo. Un datum define el elipsoide y su relación con la superficie.",
        "El mapa equirectangular del simulador conserva longitudes uniformes pero deforma áreas cerca de los polos.",
      ],
      [
        "Toda proyección plana deforma alguna propiedad.",
        "El antimeridiano requiere continuidad especial.",
      ],
      "u=(λ+π)/2π; v=1/2−φ/π",
      "https://earth-info.nga.mil/",
    ],
    [
      "Cartografía",
      "Modelos digitales de elevación",
      [
        "Un DEM almacena alturas respecto a una referencia. DSM puede incluir edificios y vegetación; DTM intenta representar el terreno desnudo.",
        "En un globo completo el relieve real apenas se percibe, por eso las visualizaciones suelen exagerarlo.",
      ],
      [
        "Altura elipsoidal y ortométrica son distintas.",
        "Las zonas sin datos requieren máscaras.",
      ],
      null,
      "https://www.earthdata.nasa.gov/topics/land-surface/topography",
    ],
    [
      "Constelaciones",
      "Diseño de constelaciones",
      [
        "Una constelación distribuye vehículos entre varios planos y fases. Se busca cobertura, revisita, redundancia y coste adecuados.",
        "Las constelaciones tipo Walker son una forma sistemática de repartir satélites.",
      ],
      [
        "Más satélites no solucionan por sí solos una mala geometría.",
        "Los planos orbitales son tan importantes como el número.",
      ],
      "Walker Δ: i : t/p/f",
      S.orbits,
    ],
    [
      "Constelaciones",
      "Escaneo coordinado",
      [
        "Varios satélites pueden dividir regiones, tiempos o tipos de sensor. La coordinación evita duplicaciones innecesarias y permite observaciones casi simultáneas.",
        "En esta simulación cada vehículo conserva órbita, FOV, apuntamiento y carga útil propios.",
      ],
      [
        "Se puede priorizar cobertura o revisita.",
        "Los datos deben fusionarse con calibración cruzada.",
      ],
      null,
      S.nasa,
    ],
    [
      "Comunicaciones",
      "Horizonte radioeléctrico",
      [
        "Una estación solo enlaza con un satélite sobre su horizonte local. La elevación mínima práctica suele ser mayor que cero para evitar obstáculos y trayectos atmosféricos largos.",
        "La altura aumenta el área visible, pero también distancia y retardo.",
      ],
      [
        "El planeta bloquea la línea de visión.",
        "El relieve local no está modelado aquí.",
      ],
      "ψ = arccos(R/(R+h))",
      "https://www.esa.int/Enabling_Support/Operations/Ground_Systems_Engineering",
    ],
    [
      "Comunicaciones",
      "Enlaces intersatelitales",
      [
        "Los enlaces ópticos o de radio entre satélites permiten transportar información sin bajar inmediatamente a tierra.",
        "El encaminamiento cambia a medida que la topología orbital evoluciona.",
      ],
      [
        "La línea debe evitar el limbo del planeta.",
        "Potencia, antena y modulación determinan el margen.",
      ],
      null,
      "https://www.esa.int/Applications/Connectivity_and_Secure_Communications",
    ],
    [
      "Comunicaciones",
      "Latencia y presupuesto de enlace",
      [
        "El límite mínimo de latencia proviene del tiempo de propagación. El retardo real añade procesado, encaminamiento y colas.",
        "Un presupuesto de enlace compara potencia recibida con sensibilidad y pérdidas.",
      ],
      ["La pérdida de espacio libre crece con distancia y frecuencia."],
      "t=d/c; FSPL=(4πd/λ)²",
      "https://www.esa.int/Applications/Connectivity_and_Secure_Communications",
    ],
    [
      "Navegación",
      "Qué es GNSS",
      [
        "GNSS es la familia de sistemas globales de navegación por satélite. GPS, Galileo, GLONASS y BeiDou transmiten tiempo y efemérides para que el receptor calcule posición, velocidad y tiempo.",
        "El satélite no “ve” directamente dónde está el teléfono: el receptor resuelve su propia posición.",
      ],
      [
        "GPS es un GNSS concreto.",
        "Galileo es el sistema europeo bajo control civil.",
      ],
      null,
      S.gnss,
    ],
    [
      "Navegación",
      "Pseudodistancias y relojes",
      [
        "El receptor compara el instante transmitido con el recibido. Como su reloj no es atómico, aparece un sesgo común que se resuelve como cuarta incógnita.",
        "Por ello hacen falta al menos cuatro satélites para una solución tridimensional con tiempo.",
      ],
      [
        "Cada nanosegundo equivale aproximadamente a 30 cm de propagación.",
        "Los mensajes incluyen correcciones de reloj.",
      ],
      "ρᵢ=‖x−sᵢ‖+c·δt",
      S.gps,
    ],
    [
      "Navegación",
      "Trilateración y geometría",
      [
        "Cada pseudodistancia define una esfera. La solución conjunta encuentra la posición compatible con las medidas.",
        "Satélites muy agrupados producen mala geometría; una distribución amplia en el cielo reduce la dilución de precisión.",
      ],
      [
        "DOP bajo suele ser mejor.",
        "Visibilidad no garantiza buena geometría.",
      ],
      "σ_pos ≈ DOP·σ_rango",
      "https://gssc.esa.int/navipedia/index.php/Positioning_Error",
    ],
    [
      "Navegación",
      "Errores GNSS",
      [
        "Ionosfera, troposfera, multitrayecto, relojes, efemérides y ruido alteran las pseudodistancias. Los receptores multifrecuencia y redes de corrección reducen varios errores.",
        "La simulación separa error de reloj, atmósfera y multitrayecto para enseñar su efecto.",
      ],
      [
        "Los cañones urbanos degradan visibilidad.",
        "La precisión real depende del receptor y del entorno.",
      ],
      null,
      "https://gssc.esa.int/navipedia/index.php/GNSS_Basic_Observables",
    ],
    [
      "Navegación",
      "GPS, Galileo y otras constelaciones",
      [
        "GPS y Galileo operan principalmente en MEO y están diseñados para cobertura global. Sus señales interoperables permiten usar más satélites y mejorar disponibilidad.",
        "Sistemas regionales y aumentaciones complementan la navegación global.",
      ],
      [
        "Galileo ofrece servicios civiles europeos.",
        "Un receptor moderno suele ser multiconstelación.",
      ],
      null,
      S.esa,
    ],
    [
      "Exploración",
      "Escanear otros mundos",
      [
        "Los principios orbitales se mantienen, pero cambian gravedad, radio, rotación, atmósfera y disponibilidad cartográfica.",
        "En lunas pequeñas la irregularidad del campo gravitatorio puede volver insuficiente el modelo de dos cuerpos.",
      ],
      [
        "Un mapa visible no es necesariamente un DEM.",
        "La cobertura conocida puede ser incompleta.",
      ],
      null,
      S.moons,
    ],
    [
      "Exploración",
      "Lunas oceánicas y mundos activos",
      [
        "Ío es volcánicamente activo; Europa, Ganímedes y Calisto presentan indicios de océanos internos; Encélado expulsa material desde su región polar sur.",
        "Cada objetivo exige instrumentos diferentes: cámaras, radar, magnetómetros, espectrómetros o altímetros.",
      ],
      [
        "La resonancia orbital puede generar calentamiento de marea.",
        "Una superficie joven conserva menos cráteres.",
      ],
      null,
      S.jmoons,
    ],
  ].map((c, i) => ({
    id: i + 1,
    section: c[0],
    title: c[1],
    paragraphs: c[2],
    bullets: c[3],
    formula: c[4],
    source: c[5],
  }));
  chapters[2].image =
    "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/content-feature/orbitscatalog/images/ellipse_diagram.png?crop=faces%2Cfocalpoint&fit=clip&h=243&w=468";
  chapters[3].image =
    "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/content-feature/orbitscatalog/images/orbits_schematic.png?crop=faces%2Cfocalpoint&fit=clip&h=240&w=720";
  chapters[29].image =
    "https://assets.science.nasa.gov/dynamicimage/assets/science/psd/solar/internal_resources/6158/Europa_from_Galileo-1.jpeg?crop=faces%2Cfocalpoint&fit=clip&h=900&w=1280";
  window.ORBITALIS_V2 = { bodies, cities, chapters };
})();
